import type { Metadata } from "next";
import { Inter, Jua, Manrope, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/front_end/Navbar";
import { cn } from "@/lib/utils";
import { Variable } from "lucide-react";
import OfflineDetector from "@/components/front_end/OfflineDetector";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jua = Jua({ weight: ["400"], subsets: ["latin"] , variable: "--font-Jua" });
const manrope = Manrope({ weight: "400", subsets: ["latin"] , variable: "--font-Manrope" });
const kumbh_sans = Kumbh_Sans({ weight: ["400","500","600","700"], subsets: ["latin"] , variable: "--font-KumbSans" });



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("md:hidden",inter.className,kumbh_sans.variable,jua.variable,manrope.variable )}>
        {/* <OfflineDetector/> */}
        {children}
      </body>
    </html>
  );
}
