import type { Metadata } from "next";
import { Inter, Jua, Manrope, Kumbh_Sans } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

const jua = Jua({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jua",
});

const manrope = Manrope({
  weight: ["400", "500", "600", "700", "800", "300", "200"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

const kumbh_sans = Kumbh_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-kumbh-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${jua.variable} ${manrope.variable} ${kumbh_sans.variable} bg-gray-100`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
