import type { Metadata } from "next";
import { Inter, Jua, Manrope, Kumbh_Sans } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { account } from "@/lib/appwrite";

const inter = Inter({ subsets: ["latin"] });

const jua = Jua({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jua",
});

const manrope = Manrope({
  weight: ["400", "500", "600", "700", "800", "300", "200"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

const kumbh_sans = Kumbh_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-kumbh-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const [laoding, setLoading] = useState(true);
  const [loggedInUser, setLoggedInUser] = useState<any>(null);

  useEffect(() => {
    const getSession = async () => {
      const x = await account.get();
      console.log(x);
      setLoggedInUser(x);
      setLoading(false);
    };
    getSession();
  }, []);

  if (laoding) {
    return <div>Loading...</div>;
  }

  if (!loggedInUser) {
    router.push("/sign-in");
  }

  return (
    <html lang="en">
      <body
        className={` ${jua.variable} ${manrope.variable} ${kumbh_sans.variable} bg-gray-100`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
